defaults:
  - train
  - _self_

idx_t0: 20
idx_t1: 180
N: 200
q: 100
discrete: True

time_domain:
  _target_: pinnstorch.data.TimeDomain
  t_interval: [0, 1]
  t_points: 201

spatial_domain:
  _target_: pinnstorch.data.Interval
  x_interval: [-1, 0.99609375]
  shape: [512, 1]

mesh:
  _target_: pinnstorch.data.Mesh
  root_dir: ${paths.data_dir}
  read_data_fn: ???
  ub: [1.0, 1.0]
  lb: [-1.0, 0.0]

runge_kutta:
  _target_: pinnstorch.models.RungeKutta
  root_dir: ${paths.rk_dir}
  q: ${q}
  t1: ${idx_t0}
  t2: ${idx_t1}
  time_domain: ${time_domain}

train_datasets:
  - mesh_sampler:
      _target_: pinnstorch.data.DiscreteMeshSampler
      _partial_: true
      num_sample: ${N}
      idx_t: ${idx_t0}
      solution:
        - u
      collection_points:
        - f
  - periodic_boundary_condition:
      _target_: pinnstorch.data.PeriodicBoundaryCondition
      _partial_: true
      idx_t: ${idx_t1}
      derivative_order: 1
      solution:
        - u
      discrete: ${discrete}

val_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.DiscreteMeshSampler
      _partial_: true
      idx_t: ${idx_t1}
      solution:
        - u

pred_dataset:
  - mesh_sampler:
      _target_: pinnstorch.data.DiscreteMeshSampler
      _partial_: true
      idx_t: ${idx_t1}
      solution:
        - u

net:
  _target_: pinnstorch.models.FCN
  layers:
    - 1
    - 200
    - 200
    - 200
    - 200
    - ${eval:'${q} + 1'}
  output_names:
    - u
  discrete: ${discrete}

model:
  loss_fn: sse
  runge_kutta: ${runge_kutta}

trainer:
  accelerator: gpu
  max_epochs: 100000
  devices: [0]
  deterministic: false
  check_val_every_n_epoch: 100001

train: true
test: false
val: true
optimized_metric:
  error:
    - u

plotting:
  _target_: pinnstorch.utils.plot_ac
  _partial_: true

seed: 1234
task_name: ac

hydra:
  searchpath:
    - pkg://pinnstorch/conf
